### ISSUE TITLE
view chat is missing

### ISSUE THREAD

**Issue by FiliusBonacci** [manoharkhadka1/laravel-chat-app#3]
after go to /chat view chat is missing...

**Comment by manoharkhadka1** [comment]
@FiliusBonacci , can you please explain little more ! I actually didn't understand correctly.

**Comment by FiliusBonacci** [comment]
sure, look at your web.php 
Route::get('/chat', function () {
    return view('chat');
});

this view doesn't exist. I found out that all things need to work are in home.blade.php so it should be 
return view('home'); instead

**Comment by manoharkhadka1** [comment]
Yes , actually 
Route::get('/chat', function () {
    return view('chat');
}); 
is just mentioned in web.php and never used anywhere..we need to hit /chat/public/home instead.
