### ISSUE TITLE
problems

### ISSUE THREAD

**Issue by aarontanzk** [manoharkhadka1/laravel-chat-app#5]
Hi  I have these problems:

1)
Failed to load resource: the server responded with a status of 404 (Not Found) chat/public/users

2)
app.js:774 Uncaught (in promise) Error: Request failed with status code 404
    at createError (app.js:774)
    at settle (app.js:11176)
    at XMLHttpRequest.handleLoad (app.js:614)

**Comment by manoharkhadka1** [comment]
are you still having the problem ? have you configured things correctly ? And also it requires php version 7.
