### ISSUE TITLE
Some issues

### ISSUE THREAD

**Issue by napestershine** [manoharkhadka1/laravel-chat-app#7]
- Not working in real time.
- files are not transferring and showing on other end
- When a new user join in it doesn't update user list on left side.

screen shots
On my System
![image](https://user-images.githubusercontent.com/8603325/33872787-4dbcbbec-df3e-11e7-944e-4703af056497.png)

On other user system
![whatsapp image 2017-12-12 at 13 11 46](https://user-images.githubusercontent.com/8603325/33872804-628d72dc-df3e-11e7-8fd9-61f32ecba512.jpeg)

TIA

**Comment by adesinah** [comment]
Please, have you been able to solve the "realtime" issue? I am having the same issue here.

**Comment by manoharkhadka1** [comment]
You have to run one of the following commands from your project directory in command prompt:

1. npm run watch
2. npm run dev
